imports_layout = "HorizontalVertical"
max_width = 80
normalize_comments = true
match_arm_blocks = false
wrap_comments = true
blank_lines_upper_bound = 2
merge_imports = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
